"""source_file_columns

Revision ID: 7c6a45873aa0
Revises: 0001_baseline
Create Date: 2026-06-30 09:56:35.875261
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic.
revision = '0002_source_file'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('source_file_key', sa.Text(), nullable=True), schema='process_ai')
    op.add_column('document_versions', sa.Column('source_file_name', sa.String(length=500), nullable=True), schema='process_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'source_file_name', schema='process_ai')
    op.drop_column('document_versions', 'source_file_key', schema='process_ai')
    # ### end Alembic commands ###
